### PR TITLE
Generate example with factory (#367)

### PR DESCRIPTION
**Pull request by kevincobain2000**
Reference: https://github.com/rakutentech/laravel-request-docs/pull/367

* Update composer to PHP greater than 8

* adds parameters for activating generation through factory

* add example generation by factories

* returns the original state

* revert index alter

* update readme

* Add example to mock

---------

### CODE REVIEW

**Comment by kevincobain2000** [comment]
To @fernandopiovezan1 
I have enabled CI tests on pull_requests too, so your next PR should be able to run the CI directly without merging to master.
Can you please check the failing tests?
Thanks

**Comment by fernando-piovezan-instar** [comment]
Hi @kevincobain2000 I made the lint corrections as requested, but the first two CIs will have to be disabled, as PHP 7.4 was removed from the composer because it used PHP 8.0 methods, so it will not be possible to make the correction as there is no compatibility.

**Comment by fernandopiovezan1** [comment]
I made the correction but it doesn't come to this commit, I don't understand what the flow should be now.
Should I open a PR for develop or master? As soon as I know where the PR goes, I'll open it again

**Comment by kevincobain2000** [comment]
I see. Hold on I ll remove that from matrix tonight

**Comment by fernandopiovezan1** [comment]
I can't send it to this PR since I lost track of my original branch, but the changes that are in this branch are now also in the other PR since I did the development rebase in my branch. So I believe this branch can be closed, as it will no longer be updated

**Pull request closed without merging**
