### PR TITLE
Added boolean and file attribute type support

### PR DESCRIPTION
**Pull request by rcerljenko**
Added support for `boolean` and `file|image` attribute types

### CODE REVIEW

**Comment by kevincobain2000** [comment]
Noted, and thanks for the contribution. Will check it over the weekend.

**Comment by kevincobain2000** [comment]
Looked cool! Thanks merged and published

**Comment by rcerljenko** [comment]
Thanks!

**Comment by rcerljenko** [comment]
@kevincobain2000 just a thought...
my company uses this library for exporting backend API routes... eg. our frontend developers can easily inspect what to pass in api requests and view responses also

would you accept a PR where we give that index page some UI overhaul? since we use Vue.js in our frontend stack, our frontend developers would be willing to give that page a little UI boost to look modern

what do you say?

**Comment by kevincobain2000** [comment]
Hi @rcerljenko 
Thanks for the support. I am glad that the library is helpful to you.
Mostly all the open issues right now are related to UI lift in one way or the other.
Yea, I'd be up for it and merge it.
The one important item about the current design is the use of HTML table, which enables us to copy it to the clipboard, it paste it as it is as a table inside Confluence/MS Teams chat etc. Apart from that, feel free to even bring major changes such use xxx instead of prism or get rid of tailwind all together.


https://github.com/rakutentech/laravel-request-docs/issues/6
https://github.com/rakutentech/laravel-request-docs/issues/16
https://github.com/rakutentech/laravel-request-docs/issues/51
https://github.com/rakutentech/laravel-request-docs/issues/52
https://github.com/rakutentech/laravel-request-docs/issues/53

**Comment by rcerljenko** [comment]
Thanks for the green light! I'll talk with my frontend team tomorrow and see if we could manage that.  :)

**Pull request merged**
