### PR TITLE
fix: method without params documents not shown

### PR DESCRIPTION
**Pull request by farshadfakhar**
I have a problem that methods without params documents not shown, and now fixed

### CODE REVIEW

**Comment by kevincobain2000** [comment]
Thanks, looks ok to me, I ll merge this soon and push the new tag

**Comment by kevincobain2000** [comment]
> I have a problem that methods without params 

Would you please elaborate a bit on what params?
Thanks

**Comment by farshadfakhar** [comment]
> 

I had to add documents for all methods in controllers, before this change this happens just for routes with params. Now documents generates for all methods

**Comment by kevincobain2000** [comment]
Pushed 1.23

**Pull request merged**
